### ISSUE TITLE
How to get data that is actions only?

### ISSUE THREAD

**Issue by dravenk** [mozilla-iot/webthing-node#113]
I downloaded and ran the project. I can get Things data from http://127.0.0.1:8888/. Whenever I want actions data, I notice that `/{thing id}/actions/{action id}` always responds to 201 Created. And `/{thing id}/actions` does not respond data.
<img width="751" alt="actions" src="https://user-images.githubusercontent.com/14295318/62408623-2b0b6b00-b5fe-11e9-9686-718f1644a8e8.png">
<img width="747" alt="empty_actions" src="https://user-images.githubusercontent.com/14295318/62408624-3199e280-b5fe-11e9-8db9-b736ea19c9c8.png">

**Comment by mrstegeman** [comment]
I'm guessing you were missing the `Accept` header on your GET. Also, the input for your action was invalid (you used `level` instead of `brightness`) -- unless you're on a super old version of the library.

```bash
$ curl \
    -w '\n%{http_code}' \
    -X POST \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    --data '{"fade":{"input":{"brightness":50,"duration":1000}}}' \
    http://localhost:8888/0/actions/fade
{"fade":{"href":"/0/actions/fade/5e496282-c4f6-4dd0-a405-57627af4ded5","timeRequested":"2019-08-03T15:42:45+00:00","status":"created","input":{"brightness":50,"duration":1000}}}
201
```

```bash
$ curl \
    -w '\n%{http_code}' \
    -H 'Accept: application/json' \
    http://localhost:8888/0/actions
[{"fade":{"href":"/0/actions/fade/5e496282-c4f6-4dd0-a405-57627af4ded5","timeRequested":"2019-08-03T15:42:45+00:00","status":"completed","input":{"brightness":50,"duration":1000},"timeCompleted":"2019-08-03T15:42:46+00:00"}}]
200
````

**Comment by dravenk** [comment]
@mrstegeman Thanks.  I was using the old specification version https://iot.mozilla.org/wot/#introduction/. I think we should update the https://github.com/mozilla-iot/wot
