### ISSUE TITLE
Don't know which files to edit

### ISSUE THREAD

**Issue by diginfo** [mozilla-iot/webthing-node#122]
Hi;

I have looked at the readme that shows various code snippets, but it does not state what files need to be updated with this code !

I have no idea where these code snippets should be added !

**Comment by mrstegeman** [comment]
You won't be editing files in the library. You'll be creating your own file that uses the provided classes.

For some examples, see here:
* https://github.com/mozilla-iot/webthing-node/tree/master/example
* https://github.com/mrstegeman/mpd-webthing/tree/master/node
* https://github.com/mrstegeman/photo-cycler-webthing/tree/master/node
* https://github.com/mrstegeman/webthing-microbit
* https://github.com/hobinjk/webthing-thingy52
