### ISSUE TITLE
How to handle action response and error running actions? 

### ISSUE THREAD

**Issue by jordanorc** [mozilla-iot/webthing-node#124]
I need some help. How to deal with actions that have any kind of response? And how to deal with action when it returns an error? 

Seen the code, it seems that `start` method calls always `finish`, even if there is an error. And it not pass the response from `performAction` to `finish` method.

There is any way to handle with these problems? Thank you!

**Comment by mrstegeman** [comment]
To handle an error, you could override `start()` from your Action subclass with something like this:

```js
start() {
  this.status = 'pending';
  this.thing.actionNotify(this);
  this.performAction()
    .then(this.finish.bind(this))
    .catch((e) => {
      console.error(e);
      this.status = 'error';
      this.thing.actionNotify(this);
    });
}
```

As for the response, actions do not have a response, according to [the spec](https://iot.mozilla.org/wot/). Instead, you could send an Event, if you need to.

**Comment by jordanorc** [comment]
Thank you very much. I'll try this. :)

**Comment by mrstegeman** [comment]
I'm going to close this issue, but feel free to comment again if you have more questions.
