### ISSUE TITLE
How to use it with gateway

### ISSUE THREAD

**Issue by apiel** [mozilla-iot/webthing-node#134]
There is no instruction to set it up with the gateway. How should we proceed?

**Comment by mrstegeman** [comment]
You'll want to install the "Web Thing" add-on. After that, your web things should be autodetected on the network like other devices, so you'll add them to the gateway as usual.

If autodetection doesn't work, you can click "Add by URL..." on the page where you add new devices and type in the URL of your web thing.

**Comment by apiel** [comment]
Would it be possible to update the readme with those information?

**Comment by mrstegeman** [comment]
Done.
