### ISSUE TITLE
Known things which type is defined as array are displayed as custom things

### ISSUE THREAD

**Issue by rzr** [mozilla-iot/webthing-node#21]
To make them displayed as before, I had to revert::
https://github.com/mozilla-iot/webthing-node/commit/82d5266393fac2eedc6f44356ae0868b8640a166

Maybe some code is pending for the gateway ?

It looks like a work in progress, so I won't investigate more, until this issue remains.

cc: @mrstegeman

**Comment by mrstegeman** [comment]
@rzr Any update on this?

**Comment by rzr** [comment]
No I think It can be closed... sorry for noise
