### ISSUE TITLE
Exposing multiple Things on the same ThingServer

### ISSUE THREAD

**Issue by DurandA** [mozilla-iot/webthing-node#4]
I want to expose multiple Things on the same port. Is it possible to create a ThingServer with multiple Things (similarly to the [Things Gateway](https://github.com/mozilla-iot/gateway) where things are accessed using */things/{thing_id}* URI)?

Maybe writing an adapter for the Things Gateway is a better option in this case. For reference, I am experimenting with a [Thingy:52](https://www.nordicsemi.com/eng/Products/Nordic-Thingy-52) to create a simple [Web Thingy](https://gist.github.com/DurandA/4396348a733bc784bd93266d4a2ac117).

**Comment by mrstegeman** [comment]
We debated whether or not we should support multiple devices with these libraries. It would be straightforward to do so, but we couldn't determine if there were any legitimate use cases for this functionality.

The obvious case is for bridge-type devices, such as the Philips Hue Hub, but for things like that, we already give developers the ability to create an adapter add-on for the Things Gateway.

I think what you've currently implemented is the right thing to do, that is, creating one device with multiple properties for the different sensors. Is there additional functionality you were hoping to implement that you can't currently?

By the way, your project is really cool!

**Comment by dhylands** [comment]
A use case that comes to mind would be something like a robot, which would have a multitude of devices/sensors.

**Comment by mrstegeman** [comment]
Yes, that would be the appropriate adapter. You'll need to build and install it manually for now, as it's not currently on the add-ons list. If you just `git clone` it into your addons directory (`~/.mozilla-iot/addons` if on master, `/path/to/gateway/build/addons` if on 0.3.X) and run `./package.sh`, that should do it.

The module will broadcast an mDNS service, which should be detected by the adapter.

**Comment by DurandA** [comment]
Many thanks!

**Comment by DurandA** [comment]
One drawback of supporting only one device is that some interfaces/drivers are not meant to be shared among several processes. As a consequence, we cannot launch several Web Thing instances sharing the same interface (e.g., some USB radio modules with no proper drivers).

**Comment by mrstegeman** [comment]
@DurandA The 0.4.0 release now has support for multiple things, but the thing-url-adapter doesn't yet.

**Comment by DurandA** [comment]
Awesome!
I did not test the thing-url-adapter yet as it crash on startup on my system. I will have a closer look.

**Comment by benfrancis** [comment]
> A use case that comes to mind would be something like a robot, which would have a multitude of devices/sensors.

FWIW, I think a robot should be a single web thing, with multiple properties, actions and events. Note that properties can be defined as objects with multiple layers of nested properties so can be quite complex if necessary. If I wanted to discover and use a robot as a web thing, I wouldn't expect to have to add each motor, servo, sensor and LED separately to my Web of Things client or gateway.

Having multiple thing endpoints for a single device is not how  a Thing Description is intended to be used (at least in my view).

I would also expect a Thingy:52 to be exposed as a single Thing. Or is there some particular reason that motivated wanting to split it?

**Comment by hobinjk** [comment]
The example that comes to mind for me is if a server in your kitchen is connected to an oven temperature sensor and a fridge light indicator. You want to be able to expose both independently without them being part of a Kitchen Supervisor thing since they make more sense on their own.

 i.e. serving multiple Thing descriptions because these are logically distinct devices that are only on the same board for convenience.

(copied from elsewhere and edited a bit)

**Comment by benfrancis** [comment]
OK, let's see what people do with it. Hopefully it is more useful than confusing.
