### ISSUE TITLE
Example with ESP32, Raspi Zero W dev boards?

### ISSUE THREAD

**Issue by kokujin** [mozilla-iot/webthing-node#87]
Can someone point me to a tutorial that shows how to use this module with an ESP32 or Raspi Zero W? Thanks

**Comment by mrstegeman** [comment]
For ESP32, you'll probably want either [webthing-arduino](https://github.com/mozilla-iot/webthing-arduino) or [webthing-upy](https://github.com/mozilla-iot/webthing-upy). There is also a tutorial [here](https://hacks.mozilla.org/2018/04/making-a-web-thing-on-the-esp8266/).

For the Raspberry Pi Zero W, you would just add this node library (`npm install --save webthing`) and use it like you would any other library. There are some examples [here](https://github.com/mozilla-iot/webthing-node/tree/master/example). There is also a tutorial [here](https://hacks.mozilla.org/2018/05/creating-web-things-with-python-node-js-and-java/).
